<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day07_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display employee_id and last_name from the 5 employees
pd.read_sql("""
SELECT employee_id, last_name
FROM employees
LIMIT 5;
""", conn)

   employee_id last_name
0            1     Patel
1            2     Patel
2            3       Das
3            4       Das
4            5       Das

In [ ]:
#Display department_id and department_name from the first 3 departments
pd.read_sql("""
SELECT department_id, department_name
FROM departments
LIMIT 3;
""", conn)

   department_id department_name
0              1              HR
1              2         Finance
2              3              IT

In [ ]:
#Display product_name, category and price from the first 3 departments
pd.read_sql("""
SELECT product_name, category, price
FROM products
LIMIT 3;
""", conn)

     product_name category    price
0  Laptop Model 1   Laptop  90499.0
1  Laptop Model 2   Laptop  90999.0
2  Laptop Model 3   Laptop  91499.0

In [ ]:
#Display customer_name and email from the first 6 customers
pd.read_sql("PRAGMA table_info(customers);", conn)

   cid         name     type  notnull dflt_value  pk
0    0  customer_id  INTEGER        0       None   1
1    1   first_name     TEXT        0       None   0
2    2    last_name     TEXT        0       None   0
3    3        email     TEXT        0       None   0
4    4        phone     TEXT        0       None   0
5    5         city     TEXT        0       None   0

In [ ]:
#Display order_id, order_date, customer_id and employee_id from the first 10 orders
pd.read_sql("PRAGMA table_info(orders);", conn)

   cid         name     type  notnull dflt_value  pk
0    0     order_id  INTEGER        0       None   1
1    1  customer_id  INTEGER        0       None   0
2    2   product_id  INTEGER        0       None   0
3    3   order_date     TEXT        0       None   0
4    4     quantity  INTEGER        0       None   0

In [ ]:
#Display the first 8 rows from the employees table showing employee_id, first_name and email