<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day09_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display employee_id and first name from the first 6 employees
pd.read_sql("""
SELECT employee_id, first_name
FROM employees
LIMIT 6;
""", conn)

   employee_id first_name
0            1      Aarav
1            2     Vivaan
2            3     Aditya
3            4       Riya
4            5      Priya
5            6       Neha

In [ ]:
#Display department_id and department_name from the first 5 departments
pd.read_sql("""
SELECT department_id, department_name
FROM departments
LIMIT 5;
""", conn)

   department_id department_name
0              1              HR
1              2         Finance
2              3              IT
3              4       Marketing
4              5           Sales

In [ ]:
#Display product_name, category and price from the first 8 products
pd.read_sql("""
SELECT product_name, category, price
FROM products
LIMIT 8;
""", conn)

     product_name category    price
0  Laptop Model 1   Laptop  90499.0
1  Laptop Model 2   Laptop  90999.0
2  Laptop Model 3   Laptop  91499.0
3  Laptop Model 4   Laptop  91999.0
4  Mobile Model 1   Mobile  30499.0
5  Mobile Model 2   Mobile  30999.0
6  Mobile Model 3   Mobile  31499.0
7  Mobile Model 4   Mobile  31999.0

In [ ]:
#Display customer_id, customer_name and email from the first 10 customers
pd.read_sql("""
SELECT customer_id, first_name, last_name, email
FROM customers
LIMIT 10;
""", conn)

   customer_id first_name last_name             email
0            1      Akash    Sharma   akash1@mail.com
1            2       Ritu       Das    ritu2@mail.com
2            3      Mohit     Kumar   mohit3@mail.com
3            4     Simran       Das  simran4@mail.com
4            5       Yash    Sharma    yash5@mail.com
5            6     Anjali     Singh  anjali6@mail.com
6            7     Deepak    Wilson  deepak7@mail.com
7            8      Komal       Roy   komal8@mail.com
8            9      Nitin     Brown   nitin9@mail.com
9           10      Aisha     Kumar  aisha10@mail.com

In [13]:
#Display order_id, customer_id, employee_id and order_date from the first 15 ordepd.
pd.read_sql("""
SELECT order_id, customer_id, product_id, order_date
FROM orders
LIMIT 15;
""", conn)

    order_id  customer_id  product_id  order_date
0          1           20           2  2025-10-15
1          2           11          16  2025-02-26
2          3           29          24  2024-01-15
3          4           17          23  2024-09-08
4          5           16           3  2024-12-14
5          6           15          20  2025-09-01
6          7            2          20  2024-05-15
7          8           13          19  2026-03-11
8          9           28           7  2025-01-10
9         10            1          10  2024-07-16
10        11           13          14  2024-12-19
11        12           26          16  2025-12-07
12        13           14          17  2026-04-14
13        14           33          19  2024-01-19
14        15           27           2  2024-10-16