<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day05_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display the first 3 rows from the department table
pd.read_sql("""
SELECT *
FROM departments
LIMIT 3;
""", conn)

   department_id department_name  manager_id   location    budget
0              1              HR           1  Bangalore  300000.0
1              2         Finance           2     Mumbai  450000.0
2              3              IT           3  Bangalore  900000.0

In [ ]:
#Display first_name and last_name from the first 5 employees
pd.read_sql("""
SELECT first_name, last_name
FROM employees
LIMIT 5;
""", conn)

  first_name last_name
0      Aarav     Patel
1     Vivaan     Patel
2     Aditya       Das
3       Riya       Das
4      Priya       Das

In [ ]:
#Display product_name and price from the first 8 products
pd.read_sql("""
SELECT product_name, price
FROM products
LIMIT 8;
""", conn)

     product_name    price
0  Laptop Model 1  90499.0
1  Laptop Model 2  90999.0
2  Laptop Model 3  91499.0
3  Laptop Model 4  91999.0
4  Mobile Model 1  30499.0
5  Mobile Model 2  30999.0
6  Mobile Model 3  31499.0
7  Mobile Model 4  31999.0

In [ ]:
#Display customer_name and city from the first 10 customers
pd.read_sql("PRAGMA table_info(customers);", conn)

   cid         name     type  notnull dflt_value  pk
0    0  customer_id  INTEGER        0       None   1
1    1   first_name     TEXT        0       None   0
2    2    last_name     TEXT        0       None   0
3    3        email     TEXT        0       None   0
4    4        phone     TEXT        0       None   0
5    5         city     TEXT        0       None   0

In [ ]:
#Display order_id, customer_id and order_date from the first 12 orders
pd.read_sql("""
SELECT order_id, customer_id, order_date
FROM orders
LIMIT 12;
""", conn)

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
5          6           15  2025-09-01
6          7            2  2024-05-15
7          8           13  2026-03-11
8          9           28  2025-01-10
9         10            1  2024-07-16
10        11           13  2024-12-19
11        12           26  2025-12-07

In [ ]:
#Display the first 7 rows from the employees table showing only employee_id, first_name and last_name