<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day08_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display only employee_id and email from the first 5 employees
pd.read_sql("""
SELECT employee_id, email
FROM employees
LIMIT 5;
""", conn)

   employee_id                      email
0            1   aarav.patel1@company.com
1            2  vivaan.patel2@company.com
2            3    aditya.das3@company.com
3            4      riya.das4@company.com
4            5     priya.das5@company.com

In [ ]:
#Display department_name from the first 4 department
pd.read_sql("""
SELECT department_name
FROM departments
LIMIT 4;
""", conn)

  department_name
0              HR
1         Finance
2              IT
3       Marketing

In [ ]:
#Display product_id, product_name and category from the first 6 products
pd.read_sql("""
SELECT product_id, product_name, category
FROM products
LIMIT 6;
""", conn)

   product_id    product_name category
0           1  Laptop Model 1   Laptop
1           2  Laptop Model 2   Laptop
2           3  Laptop Model 3   Laptop
3           4  Laptop Model 4   Laptop
4           5  Mobile Model 1   Mobile
5           6  Mobile Model 2   Mobile

In [ ]:
#Display order_id, customer_id, employee_id and order_date from the first 12 orders
pd.read_sql("""
SELECT order_id, customer_id, order_date
FROM orders
LIMIT 12;
""", conn)

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
5          6           15  2025-09-01
6          7            2  2024-05-15
7          8           13  2026-03-11
8          9           28  2025-01-10
9         10            1  2024-07-16
10        11           13  2024-12-19
11        12           26  2025-12-07

In [ ]:
#Display the first 10 rows from the products table showing product_name and price only
pd.read_sql("""
SELECT product_name, price
FROM products
LIMIT 10;
""", conn)

         product_name    price
0      Laptop Model 1  90499.0
1      Laptop Model 2  90999.0
2      Laptop Model 3  91499.0
3      Laptop Model 4  91999.0
4      Mobile Model 1  30499.0
5      Mobile Model 2  30999.0
6      Mobile Model 3  31499.0
7      Mobile Model 4  31999.0
8  Headphones Model 1   5499.0
9  Headphones Model 2   5999.0