<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day04_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display only the department_name column from the department table
pd.read_sql("""
SELECT department_name
FROM departments;
""", conn)

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [ ]:
#Display only first_name and email from the employees table
pd.read_sql("""
SELECT first_name, email
FROM employees;
""", conn)

   first_name                       email
0       Aarav    aarav.patel1@company.com
1      Vivaan   vivaan.patel2@company.com
2      Aditya     aditya.das3@company.com
3        Riya       riya.das4@company.com
4       Priya      priya.das5@company.com
5        Neha    neha.taylor6@company.com
6       Rahul      rahul.roy7@company.com
7        Amit       amit.roy8@company.com
8        John     john.brown9@company.com
9        Emma    emma.kumar10@company.com
10       Noah    noah.singh11@company.com
11     Olivia    olivia.roy12@company.com
12       Liam    liam.singh13@company.com
13     Sophia    sophia.roy14@company.com
14     Ananya  ananya.singh15@company.com
15      Karan  karan.taylor16@company.com
16      Rohan   rohan.singh17@company.com
17      Sneha  sneha.sharma18@company.com
18      David   david.singh19@company.com
19       Sara   sara.taylor20@company.com
20      Arjun  arjun.taylor21@company.com
21       Isha      isha.roy22@company.com
22      Kabir  kabir.sharma23@company.com
23      Meera   meera.singh24@company.com
24     Vikram    vikram.roy25@company.com
25      Nisha  nisha.sharma26@company.com
26     Daniel    daniel.roy27@company.com
27      Grace   grace.brown28@company.com
28      Aryan     aryan.das29@company.com
29      Pooja  pooja.sharma30@company.com

In [ ]:
#Display product_name and price from the products table
pd.read_sql("""
SELECT product_name, price
FROM products;
""", conn)

          product_name    price
0       Laptop Model 1  90499.0
1       Laptop Model 2  90999.0
2       Laptop Model 3  91499.0
3       Laptop Model 4  91999.0
4       Mobile Model 1  30499.0
5       Mobile Model 2  30999.0
6       Mobile Model 3  31499.0
7       Mobile Model 4  31999.0
8   Headphones Model 1   5499.0
9   Headphones Model 2   5999.0
10  Headphones Model 3   6499.0
11  Headphones Model 4   6999.0
12     Monitor Model 1  16499.0
13     Monitor Model 2  16999.0
14     Monitor Model 3  17499.0
15     Monitor Model 4  17999.0
16    Keyboard Model 1   2499.0
17    Keyboard Model 2   2999.0
18    Keyboard Model 3   3499.0
19    Keyboard Model 4   3999.0
20       Mouse Model 1   1499.0
21       Mouse Model 2   1999.0
22       Mouse Model 3   2499.0
23       Mouse Model 4   2999.0
24      Camera Model 1  46499.0

In [ ]:
#Display customer_name and city from the customers table
pd.read_sql("SELECT * FROM customers LIMIT 5;", conn)

   customer_id first_name last_name             email       phone       city
0            1      Akash    Sharma   akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das    ritu2@mail.com  9627404182  Bangalore
2            3      Mohit     Kumar   mohit3@mail.com  9208428912     Mumbai
3            4     Simran       Das  simran4@mail.com  9979444461    Chennai
4            5       Yash    Sharma    yash5@mail.com  9426111115       Pune

In [ ]:
#Display order_id, customer_id and order_date from the orders table
pd.read_sql("""
SELECT order_id, customer_id, order_date
FROM orders;
""", conn)

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
..       ...          ...         ...
95        96           24  2026-03-28
96        97           32  2024-10-06
97        98           35  2025-02-24
98        99            4  2024-09-19
99       100           32  2024-07-13

[100 rows x 3 columns]

In [ ]:
#Display product_id, product_name and category from the products table