<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day15_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display customer whose city is IN (Bangalore, Mumbai)
pd.read_sql("""
SELECT *
FROM customers
WHERE city IN ('Bangalore', 'Mumbai');
""", conn)

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2            3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
3           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
4           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
5           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
6           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai

In [ ]:
#Display products whose category is IN (electronics, furniture)
pd.read_sql("""
SELECT *
FROM products
WHERE category IN ('Electronics', 'Furniture');
""", conn)

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [ ]:
#Display employees whose department_id is IN (1,2)
pd.read_sql("""
SELECT *
FROM employees
WHERE department_id IN (1, 2);
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
2,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
3,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
4,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
5,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com

In [ ]:
#Display orders whose customer_id is IN (1,2,3)
pd.read_sql("""
SELECT *
FROM orders
WHERE customer_id IN (1, 2, 3);
""", conn)

   order_id  customer_id  product_id  order_date  quantity
0         7            2          20  2024-05-15         2
1        10            1          10  2024-07-16         5
2        52            2          23  2026-01-31         4
3        66            2           3  2024-08-03         4
4        80            3           6  2024-01-26         2
5        84            3           4  2025-06-19         1
6        89            3           1  2026-03-29         1

In [ ]:
#Display employee_id , first_name and last_name for employees whose department_id is IN (1,2)
pd.read_sql("""
SELECT employee_id, first_name, last_name
FROM employees
WHERE department_id IN (2, 3);
""", conn)

   employee_id first_name last_name
0            2     Vivaan     Patel
1            3     Aditya       Das
2           12     Olivia       Roy
3           13       Liam     Singh
4           22       Isha       Roy
5           23      Kabir    Sharma